hw_dj_proj/content/urls.py
from django.urls import path
from .views import add_author, add_quote, user_quotes_list, author_details_user

app_name = 'content'

urlpatterns = [
    path('add-author/', add_author, name='add_author'),
    path('add-quote/', add_quote, name='add_quote'),
    path('user-quotes/', user_quotes_list, name='user_quotes_list'),
    path('user-author/<str:id_>/', author_details_user, name='author_details_user'),
]

hw_dj_proj/content/models.py
from django.db import models
from django.conf import settings

class Author(models.Model):
    name = models.CharField(max_length=100)
    born_date = models.DateField(null=True, blank=True) 
    born_location = models.CharField(max_length=100, blank=True) 
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.text




hw_dj_proj/content/forms.py
from django import forms
from .models import Author, Quote

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['text', 'author']




hw_dj_proj/content/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm
from .models import Quote
from django.http import HttpResponseNotFound
from .models import Author

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('content:add_quote')
    else:
        form = AuthorForm()
    return render(request, 'content/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user 
            quote.save()
            return redirect('content:user_quotes_list') 
    else:
        form = QuoteForm()
    return render(request, 'content/add_quote.html', {'form': form})

def user_quotes_list(request):
    user_quotes = Quote.objects.filter(user__isnull=False)
    return render(request, 'content/user_quotes_list.html', {'user_quotes': user_quotes})

def author_details_user(request, id_):
    try:
        author = Author.objects.get(pk=id_) 
        return render(request, 'content/author_details_user.html', {'author': author})
    except Author.DoesNotExist:
        return HttpResponseNotFound("Author not found")
    except ValueError:
        return HttpResponseNotFound("Invalid ID format")




hw_dj_proj/content/templates/content/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

  <h2>Add Author</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
  </form>
  
{% endblock %}

hw_dj_proj/content/templates/content/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

  <h2>Add quote</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
  </form>

{% endblock %}

hw_dj_proj/content/templates/content/author_details_user.html
{% extends 'quotes/base.html' %}

{% block content %} 

<div class="author-details">
    <h3 class="author-title">{{ author.author }}</h3>
    <p><strong>Born:</strong> 
        <span class="author-born-date">{{ author.born_date }}</span> 
        <span class="author-born-location">{{ author.born_location }}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

hw_dj_proj/content/templates/content/user_quotes_list.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Цитати користувачів</h1>

{% for quote in user_quotes %}
<div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
    <span class="text" itemprop="text">“{{ quote.text }}”</span>
    <span>by <small class="author" itemprop="author">{{ quote.author.name }}</small>
    <a href="{% url 'content:author_details_user' quote.author.id %}" previewlistener="true">(about)</a>
    </span>
    <div class="tags">
        Tags:
        <meta class="keywords" itemprop="keywords" content="{{ quote.keywords|join:',' }}"> 

        {% for keyword in quote.keywords %}
            <a class="tag" href="{% url 'keyword_detail' keyword %}" previewlistener="true">{{ keyword }}</a>
        {% endfor %}
    </div>
</div>
{% empty %}
    <p>Цитати відсутні.</p>
{% endfor %}

{% endblock %}